# Generated by Django 5.1.6 on 2025-03-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
