# Generated by Django 5.1.6 on 2025-03-07 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.brand'),
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.category'),
        ),
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.ManyToManyField(related_name='orders', to='store.color'),
        ),
    ]
