# Generated by Django 5.1.6 on 2025-03-12 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_authtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
