# Generated by Django 5.1.6 on 2025-03-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_cart_brand_remove_cart_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='selected_color',
            new_name='color',
        ),
    ]
