# Generated by Django 5.1.6 on 2025-05-17 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_shop_employee_product_shops_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custom_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('custom_stock', models.IntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='store.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='store.shop')),
            ],
            options={
                'unique_together': {('shop', 'product')},
            },
        ),
    ]
