# Generated by Django 5.1.6 on 2025-05-17 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_shopinventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shops',
        ),
    ]
