# Generated by Django 5.1.6 on 2025-05-17 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_remove_product_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to='store.shop'),
        ),
    ]
