# Generated by Django 5.1.5 on 2025-09-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_product_created_by_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSummary',
            fields=[
            ],
            options={
                'verbose_name': '📊 Sales Summary',
                'verbose_name_plural': '📊 Sales Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.order',),
        ),
        migrations.AddField(
            model_name='color',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='colors/'),
        ),
    ]
