# Generated by Django 5.1.5 on 2025-09-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolorimage',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
