# Generated by Django 5.2.6 on 2025-09-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_size_alter_productcolorimage_stock_cartitem_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='App Logo', max_length=100)),
                ('image', models.ImageField(upload_to='logos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
