# Generated by Django 5.1.5 on 2025-10-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_aboutpagecontent_blog_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
